### ISSUE TITLE
rubrik_assign_sla 

### ISSUE THREAD

**Issue by FrankMauroJr** [rubrikinc/rubrik-modules-for-ansible#95]
When I use the "rubrik_assign_sla" plugin I had a problem when I type the server name (node) as small letters and in Rubrik they were capitalized. 

**Describe the solution you'd like**

I would like the plugin to look for the name in Rubrik as small or capitalize.

**Describe alternatives you've considered**

I check Rubrik to see if the server name is in small or capitalized letters.

**Comment by drew-russell** [comment]
@FrankMauroJr can you provide more detail or an example playbook here?

By `server name (node)` are you referring to a Rubrik cluster node? Or does server name represent something like a physical host the Rubrik cluster is protecting?

**Comment by FrankMauroJr** [comment]
Virtual machine name.

Frank

**Comment by drew-russell** [comment]
Going to mark this as `resolution-by-design` since we want to keep the `object_name` field case-sensitive since there are certain situations where this is required. For example,

* `vCenter A` has a VM named `Demo-01`
* `vCenter B` has a VM named `demo-01`

In this example, both vCenter instances are connected to the same Rubrik cluster. So if searched for `Demo-01` but added a `.lower()` method to the search (which is the only way I can think of solving this) it would return results for both VM names which is not the desired outcome -- or rather would return an error that there are multiple VMs that match that name.

Let me know if there is something I am not thinking of and you want me to reopen.

**Comment by FrankMauroJr** [comment]
I understand.

Thanks,
Frank
